# Generated by Django 3.1.5 on 2021-01-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/images', verbose_name='Image')),
                ('slug', models.CharField(max_length=20, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'FirstSlide',
                'verbose_name_plural': 'FirstSlides',
            },
        ),
    ]
